export const tdmRequirements = [
  'addCarrier',
  'addCostLineItemOnly',
  'addCostRateLineItem',
  'addCustomer',
  'addDriver',
  'addFacility',
  'addOrderInvoice',
  'addPower',
  'addRateLineItemOnly',
  'addTrailer',
  'addVendorAndOrderInvoice',
  'addVendorInvoice',
  'apiTruckMatch',
  'attachCarrierAndVendor',
  'attachCarrierOnly',
  'attachStopsOnly',
  'createOfferOnly',
  'dispatchedWithNoStopEvents',
  'ediTruckMatch',
  'stopEventDeliveryArrivalOnly',
  'stopEventDeliveryDepartureOnly',
  'stopEventPickUpArrivalOnly',
  'stopEventPickUpDepartureOnly',
];

export const dataType = [
  'api',
  'carrier',
  'customer',
  'driver',
  'edi',
  'facility',
  'load',
  'power',
  'trailer',
];