export const staticData = {
  test: {
    orderRefCommon: 'QAREGLOAD',
    defaultTrailerType: 'Van',
    defaultLoadActivationStatus: 'Active',
    defaultTransportModeId: 'Truck',
    defaultSizeId: 'FTL',
    defaultDivision: 'Brokerage',
    defaultDriverAssignment: 'NO',
    defaultChargeType: 'Lumper',
    defaultChargePerItem: 100,
    defaultCostUnits: 1,
    defaultInvoiceStatus: 'Approved',
    defaultInvDistributionMethod: 'Print',
    defaultPaymentTerms: 'Approved',
    carrierInsurance: {
      expirationDate: '{{expirationDate}}',
      identification: 'INS383883',
      insurer: 'TRAVELERS',
      limit: 999999999,
      producer: 'GEICO',
      carrierInsuranceTypeId: 'Cargo',
      effectiveDate: '{{effectiveDate}}',
      cancelDate: null,
      underwriterRating: 'APlusPlus',
    },
  },
  dev: {
    orderRefCommon: 'QAREGLOAD',
    defaultTrailerType: 'Van',
    defaultLoadActivationStatus: 'Active',
    defaultTransportModeId: 'Truck',
    defaultSizeId: 'FTL',
    defaultDivision: null,
    defaultDriverAssignment: 'NO',
    defaultChargeType: 'Lumper',
    defaultChargePerItem: 100,
    defaultCostUnits: 1,
    defaultInvoiceStatus: 'Approved',
    defaultInvDistributionMethod: 'Print',
    defaultPaymentTerms: 'Approved',
    carrierInsurance: {
      expirationDate: '{{expirationDate}}',
      identification: 'INS383883',
      insurer: 'TRAVELERS',
      limit: 999999999,
      producer: 'GEICO',
      carrierInsuranceTypeId: 'Cargo',
      effectiveDate: '{{effectiveDate}}',
      cancelDate: null,
      underwriterRating: 'APlusPlus',
    },
  },
  td: {
    orderRefCommon: 'QAREGLOAD',
    defaultTrailerType: 'Van',
    defaultLoadActivationStatus: 'Active',
    defaultTransportModeId: 'Truck',
    defaultSizeId: 'FTL',
    defaultDivision: 'Brokerage',
    defaultDriverAssignment: 'NO',
    defaultChargeType: 'Lumper',
    defaultChargePerItem: 100,
    defaultCostUnits: 1,
    defaultInvoiceStatus: 'Approved',
    defaultInvDistributionMethod: 'Print',
    defaultPaymentTerms: 'Approved',
    carrierInsurance: {
      expirationDate: '{{expirationDate}}',
      identification: 'INS383883',
      insurer: 'TRAVELERS',
      limit: 999999999,
      producer: 'GEICO',
      carrierInsuranceTypeId: 'Cargo',
      effectiveDate: '{{effectiveDate}}',
      cancelDate: null,
      underwriterRating: 'APlusPlus',
    },
  },
  todayCount: 0,
  driverAddress: {
    typeTerm: 'Domicile',
    street1: 'Street1',
    city: 'Schenectady',
    state: 'NY',
    postalCode: '12345',
    country: 'USA',
  },
};

export const staticAssets = {
  test: {
    customerCodeCommon: 'ANC01',
    pickUpFacilityCodeCommon: 'SRF01',
    deliveryFacilityCodeCommon: 'NTFAC01',
    carrierCodeCommon: 'FYC01',
    facilityCodeCommon: 'SRF01',
    facilityWithMultiLoads: 'SRF01',
    carrierWithMultiLoads: 'FYC01',
    approvedCarrierCertCTPAT: 'UB5A86CD',
    facilityWithWasillaAK: 'WSL001',
    facilityWithBolingbrookIL: 'BGB001',
    doNotLoadVendor: 'LHE01',
    onHoldVendor: 'ATLC01',
    onDeniedVendor: 'ABFFC01',
    notApprovedVendor: 'LLV01',
    arePendingVendor: 'PTV01',
    tentantExpVendor: 'ACIV01',
    expInsuranceVendor: 'BHCV01',
    insufficientVendor: 'BQLV01',
    customerWithInvMethEDI: 'MBC01',
    vendorCodeCommon: 'MTAB01',
    facilityWithSitkaAK: 'SKA001',
    facilityWithBoiseID: 'BSE001',
    facilityWithFairbanksAK: 'FBK001',
    facilityWithSeattleWA: 'STL001',
    facilityWithAnchorageAK: 'ARG001',
    facilityWithTallahasseeFL: 'TLH001',
    facilityWithJuneauAK: 'JNE001',
    facilityWithMesaAZ: 'MSA001',
    facilityWithLincolnNE: 'LCL001',
    facilityWithHelenaMT: 'HNM001',
    facilityWithLasCrucesNM: 'LCU001',
    facilityWithPortlandOR: 'PTL001',
    facilityWithAlbuquerqueNM: 'AQU001',
    facilityWithAtlantaGA: 'ATA001',
    facilityWithScottsbluffNE: 'SBL001',
    facilityWithPhoenixAZ: 'PEN001',
    facilityWithOmahaNE: 'OHA001',
    facilityWithRenoNV: 'RNO001',
    facilityWithSanBernardinoCA: 'SBR001',
    facilityWithChapelHillNC: 'CPL001',
    facilityWithLosAngelesCA: 'AGL001',
    facilityWithScottsdaleAZ: 'DLA001',
    facilityWithMiamiFL: 'MMI001',
    facilityWithTempeAZ: 'TPE001',
    facilityWithDallasTX: 'DLS001',
    facilityWithTucsonAZ: 'TCS001',
    facilityWithDesMoinesIA: 'MNE001',
    facilityWithChicagoIL: 'CCA001',
    facilityWithMexicoCityCMX: 'VO9G8OSK',
    facilityWithQuebecQC: 'E8UK2N09',
    facilityWithSpoonerWI: '9IZW17ZG',
    customerWithInvMethNoPrint: 'PF4FMFT0',
    customerWithInvMethEmail: '4S5UX3SV',
  },

  dev: {
    customerCodeCommon: 'NINBROSQE',
    pickUpFacilityCodeCommon: 'OMPAINTSQE',
    deliveryFacilityCodeCommon: 'LINCPAINTSQE',
    carrierCodeCommon: 'NINTRUCKS',
  },
  td: {
    customerCodeCommon: 'NINBROSQE',
    pickUpFacilityCodeCommon: 'OMPAINTSQE',
    deliveryFacilityCodeCommon: 'LINCPAINTSQE',
    carrierCodeCommon: 'NINTRUCKS',
  },
};

export const minionDataValues = {
  minionDrpDwnContainerProgramTerm: 'containerProgram',
  minionDrpDwnMakeTerm: 'trailerGeneralInformationMake',
  minionDrpDwnModelTerm: 'trailerGeneralInformationModel',
  minionDrpDwnTypeTerm: 'trailerType',
};