---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
# on: workflow_dispatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ##########################################
      # Install the node modules and Run Lint#
      ##########################################

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install
        run: npm ci --no-optional

      - name: Lint
        run: npm run lint
      
      - name: "Lint JSON files"
        run: |
          npm install -g jsonlint-cli
          jsonlint-cli ../../cypress/*.json